
DOCUMENTS =  \
	blank-letterhead.pdf \
	contact-form.pdf \
	donation-form.pdf \
	dropbox-dues.pdf \
	dues-envelope.pdf \
	guest-sign-sheet.pdf \
	insurance-2012-08-31.pdf \
	insurance-2012-11-07.pdf \
	uakron-donation-letter.pdf \
	waiver.pdf \
	wifi.pdf 

CLEANUP=*.log *.aux *.out

include ../Makefile
