SUBDIRS:=$(dir ${shell find -mindepth 2 -name Makefile -print})
SUBCLEAN=$(addsuffix .clean,$(SUBDIRS))
DOCCLEAN=$(addsuffix .clean,$(DOCUMENTS))
EXTRACLEAN=*.version.latex.clean $(addsuffix .clean,$(CLEANUP))
export ROOT := $(dir $(lastword $(MAKEFILE_LIST)))
TEXINPUTS:=.:$(PWD):$(TEXINPUTS):$(ROOT)/common/

.PHONY: all $(SUBDIRS) clean $(SUBCLEAN) $(CLEANUP) $(DOCCLEAN)

all: $(DOCUMENTS) $(SUBDIRS)

clean: $(SUBCLEAN) $(DOCCLEAN) $(EXTRACLEAN)

$(SUBDIRS):
	$(MAKE) $(MFLAGS) -C $@

$(EXTRACLEAN) $(DOCCLEAN): %.clean:
	rm -vf $*

$(SUBCLEAN): %.clean:
	$(MAKE) $(MFLAGS) -C $* -f $(ROOT)/Makefile clean

%.pdf: %.svg
		inkscape -z -T -A $@ $<

%.pdf: %.latex %.version.latex $(ROOT)/common/synhak.cls $(ROOT)/impress/logo/logo.pdf
		cd $(dir $<) && TEXINPUTS=${TEXINPUTS} pdflatex -output-format=pdf $(notdir $<) </dev/null

%.version.latex: ../.git/logs/HEAD
	echo "%%% This file is generated by Makefile.\n" >> $@
	echo "%%% Do not edit!\n" >> $@
	git log -1 --format="format:\
			\\gdef\\GITAbrHash{%h}\
			\\gdef\\GITAuthorDate{%ad}\
			\\gdef\\GITAuthorName{%an}" $*.latex >> $@
	git status -s $*.latex | grep ?? && echo "\\gdef\\GITAbrHash{UNCOMMITTED}\\gdef\\GITAuthorDate{??/??/??}\\gdef\\GITAuthorName{${USER}@${HOSTNAME}}" >> $@ || exit 0
	git status -s $*.latex | grep ^A && echo "\\gdef\\GITAbrHash{UNCOMMITTED}\\gdef\\GITAuthorDate{??/??/??}\\gdef\\GITAuthorName{${USER}@${HOSTNAME}}" >> $@ || exit 0

%.png: .svg
	inkscape -e $@ $<
