\ProvidesClass{synhak-envelope}
\LoadClass{letter}
\usepackage[left=0.3in,top=0.3in,papersize={4.125in,9.5in},landscape,twoside=false]{geometry}
\usepackage{setspace}
\usepackage{graphicx}
\setlength\parskip{0pt}
\pagestyle{empty}

\def \maketitle {%
\includegraphics[width=3cm]{../impress/logo/logo}

SYNHAK

48 S. Summit St.

Akron, OH, \ 44308

\vspace{1.0in}\large

\setlength\parindent{3.6in}
}
