DOCUMENTS = \
	bullitenboard.pdf \
	donation-box.pdf \
	events.pdf \
	last-out-procedure.pdf \
	lavatories.pdf \
	main-room-right.pdf \
	main-sign.pdf \
	perkins-sign.pdf \
	perkins-sign-left.pdf \
	safety-cabinet.pdf \
	welcome.pdf

CLEANUP=*.log *.aux *.out

include ../Makefile
